### ISSUE TITLE
asn1.js is not compatible with safari implementation of strict mode

### ISSUE THREAD

**Issue by steeeveb** [indutny/asn1.js#36]
I have a browserify project which depends on Mathjs(which depends on decimal.js). My app works correctly on every browser, but not on safari. It turned out that the cause is an error with the strict mode:

SyntaxError: Cannot declare a parameter named 'k' in strict mode 

After looking inside the minification process, and inside the browserify generated code, I found that the code which generate the error is this one

https://github.com/indutny/asn1.js/blob/master/lib/asn1/base/node.js#L225

It is a known bug of safari implementation of strict mode. A function cannot have a parameter with the same name, the key() function in asn1/base/node module.

see the discussion here https://github.com/mishoo/UglifyJS2/issues/179

**Comment by indutny** [comment]
Should be fixed now, I guess: c75d861e705df9559bf572e682552278b98a218d ?

**Comment by steeeveb** [comment]
It works! thank you very much!

**Comment by indutny** [comment]
You are welcome.
