### ISSUE TITLE
Cannot use 'optional' and 'use'

### ISSUE THREAD

**Issue by felix** [indutny/asn1.js#45]
Encoding seems to work, decoding does not work. A test case is here https://github.com/felix/asn1.js/commit/ea45c619f70b00e20762b433c5494a37077da263

**Comment by felix** [comment]
der._peekTag() needs to find it, or, Node.decode() needs to test for `state.use !== null` and act accordingly.
I think.

**Comment by indutny** [comment]
Hm... I wonder if it is ok in ASN.1 to have an optional use of some struct without explicit/implicit tagging. Do you have any examples of this in RFCs, or whatever?

**Comment by felix** [comment]
I am doing a lot from RFC 4210 which has some different examples:

in 5.1.1:

    protectionAlg   [1] AlgorithmIdentifier     OPTIONAL
in 5.3.4:

    certifiedKeyPair    CertifiedKeyPair    OPTIONAL

neither of which work with `optional()` and `use()`

**Comment by indutny** [comment]
First one has `[1]` which means EXPLICIT (or IMPLICIT, I always confuse these two).

5.3.4 looks legit, though. I'll look into how it could be fixed. Thank you for the report!

**Comment by indutny** [comment]
Oh, I see that the first one does not work for you either... It is rather odd, but I'm going to check it too.

**Comment by felix** [comment]
Yeah, neither work for me. It just means I have to copy schemas inline rather than 'use'ing them which become a hassle.

**Comment by indutny** [comment]
I have landed your test and fixed it in asn1.js@2.1.2 . May I ask you to give it a try with both of your last samples from RFC, and let me know if they work for you? If they don't please submit a new test case ;) It will help a lot!

**Comment by felix** [comment]
It all works, fantastic! Thanks.

**Comment by indutny** [comment]
Cool, thank you!
