### ISSUE TITLE
result is not defined in decodeObjid

### ISSUE THREAD

**Issue by TheSharpieOne** [indutny/asn1.js#56]
`result` is never defined: https://github.com/indutny/asn1.js/blob/v4.2.1/lib/asn1/decoders/der.js#L185-L193

In the browser (asn1.js is used [eventually through dependencies] by crypto-browserify) this is causing issues.

Not sure if it was intentionally not defined or not. It was in the [initial commit](https://github.com/indutny/asn1.js/commit/eb0009c45912dbe17e35b98b5e7fbe4d50160f03#diff-1f7c5d70cc84690f90c4da96586af66dR90) and I find it difficult to believe it has not come up before.

**Comment by indutny** [comment]
Nice catch! Do you want t submit PR for this?
