### ISSUE TITLE
Fix seqof/setof when optional

### ISSUE THREAD

**Issue by felix** [indutny/asn1.js#62]
When `seqof()` is used with `optional()` the decoded results are not parsed or included in the resulting object. PR #61 updates _peekTag() to check for seqof/setof when optional. The added tests highlight the issue.

**Comment by indutny** [comment]
What is this issue for?

**Comment by felix** [comment]
Opps, sorry @indutny, updated issue description now.

**Comment by felix** [comment]
Do you need more details @indutny ?

**Comment by indutny** [comment]
@felix sorry for delay. Landed that patch! Should this issue be closed now?
