### ISSUE TITLE
Linting: `err` is not defined

### ISSUE THREAD

**Issue by vizath** [indutny/asn1.js#63]
Hello,
I do not know your codebase enough to know what would be the correct returned value.
https://github.com/indutny/asn1.js/blob/master/lib/asn1/base/node.js#L367

Thanks.

**Comment by indutny** [comment]
Hello!

Thank you for reporting it. That code wasn't used, and couldn't be triggered. But I decided to remove it anyway to stop the confusion.

Thanks again,
Fedor.
