### ISSUE TITLE
Either default to 'der' encoding/decoding or throw a meaningful error

### ISSUE THREAD

**Issue by felix** [indutny/asn1.js#69]
Either option is trivial to implement but this would save a lot of time when an encoding is not explicitly specified. Since BER is not implemented and PEM is not as popular then DER would be a good default. But it is probably better to just throw an error. ATM it just complains about something else being 'undefined', not particularly helpful.

Give a preference and I will make a PR.

**Comment by indutny** [comment]
Let's do DER.
