### ISSUE TITLE
Not able to install asn1.js-rfc2560 v4.0.1

### ISSUE THREAD

**Issue by ben-pushspring** [indutny/asn1.js#76]
Hi,
I'm running into an issue with a package that uses your module. I'm able to install v4.0.0 fine, but when I try to install the recently released 4.0.1, I receive 

npm ERR! node v4.2.2
npm ERR! npm  v2.15.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: asn1.js-rfc5280@'>=4.4.0 <5.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.0.2","1.0.3","1.2.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'asn1.js-rfc2560'

Looks like the new package.json has an invalid dependency
> "asn1.js-rfc5280": "^4.4.0"

**Comment by djres88** [comment]
Having this issue, too.

**Comment by chriskinsman** [comment]
Having this issue also.  Looks like the pull request fixes it...

**Comment by mschoendorf** [comment]
I'm also having this issue, and the dependency isn't mine (it's a dependency of a dependency) so I can't npm install until this is fixed as a patch.

**Comment by indutny** [comment]
Yikes, sorry for this! The fix has been already landed and a new version has been released. So sorry to break your builds!
