### ISSUE TITLE
NPM packaged versions after 4.8.0 do not include the RFC directory

### ISSUE THREAD

**Issue by cheburashka** [indutny/asn1.js#85]
When installing asn1.js with ```npm install asn1.js``` I noticed that unless I set the version to 4.8.0 the rfc directory is not included under node_modules/asn1.js and I can't parse X.509 certificates. Is this a packaging bug or is it intentional and if so, what is the recommended way to decode a certificate with the latest version?

**Comment by indutny** [comment]
Sorry, but this is by design.

These modules are distributed separately on npm: https://www.npmjs.com/package/asn1.js-rfc5280
