### ISSUE TITLE
Unexpected token on version 4.10.0

### ISSUE THREAD

**Issue by SamuelBeliveau** [indutny/asn1.js#91]
Since I got the latest version, my webpack build now fails.

```
Unexpected token: name (len) [./~/asn1.js/lib/asn1/decoders/der.js:58,0][vendor.js:93723,6]
  in undefined
```

My dependency tree is
```
`-- webpack@2.6.1
  `-- node-libs-browser@2.0.0
    `-- crypto-browserify@3.11.0
      `-- browserify-sign@4.0.4
        `-- parse-asn1@5.1.0
          `-- asn1.js@4.10.0
```

**Comment by indutny** [comment]
I've just tried it with webpack@2.7.0 and 3.x and it appears to be working... If it might be possible to isolate - would you care to share some code that reproduces the issue?

**Comment by indutny** [comment]
FWIW, the code at that line looks pretty normal:

```js
  let len = derDecodeLen(buffer,
    decodedTag.primitive,
    'Failed to get length of "' + tag + '"');
```

**Comment by SamuelBeliveau** [comment]
I'll see what I can do. Maybe that part of the build doesn't understand es6 constructs...

**Comment by robbinjanssen** [comment]
Not sure but having the same problem, uglify-js is the one who generates the error.

```

ERROR in js/vendor.876e7517549e49515645.js from UglifyJs
Unexpected token: name (len) [./~/asn1.js/lib/asn1/decoders/der.js:58,0][js/vendor.876e7517549e49515645.js:37953,6]

```

**Comment by indutny** [comment]
I can reproduce it too now! Had to use `-p` flag for webpack to enable uglify. Let's see what's causing it.

**Comment by indutny** [comment]
Okay, I think I'm going to unpublish the update and do a major bump. It looks like the babel is mandatory now and wasn't mandatory before.

**Comment by indutny** [comment]
Alright, all is unpublished now. Thank you for reporting. Please let me know if the error persists.

**Comment by robbinjanssen** [comment]
Solved my problems, thanks 👍

**Comment by SamuelBeliveau** [comment]
Fixed my problem, too. Thanks.
