### ISSUE TITLE
missed version 4.10.0 in Yarn

### ISSUE THREAD

**Issue by killanaca** [indutny/asn1.js#92]
Hi
version 4.10.0 of the package is missing in yarn https://github.com/yarnpkg/yarn/issues/4821

**Comment by fanatid** [comment]
`4.10.0` was unpublished
https://github.com/indutny/asn1.js/issues/91#issuecomment-340816427
https://github.com/indutny/asn1.js/issues/89#issuecomment-340906206

**Comment by indutny** [comment]
That's right. It was unpublished and released as 5.0.0.
